.PHONY: help run dev start migrate migration rollback install freeze test

# Default target
help:
	@echo "Available commands:"
	@echo ""
	@echo "  make run                        - Start dev server (uses active venv)"
	@echo "  make dev                        - Start dev server on 0.0.0.0:8000"
	@echo "  make start                      - Start dev server using .venv directly"
	@echo ""
	@echo "  make install                    - Install dependencies from requirements.txt"
	@echo "  make freeze                     - Overwrite requirements.txt with current packages"
	@echo ""
	@echo "  make migrate                    - Apply all pending migrations"
	@echo "  make migration MSG=\"description\" - Create a new autogenerated migration"
	@echo "  make rollback                   - Roll back the last migration"
	@echo ""
	@echo "  make test                       - Run test suite"

# Start the development server (requires venv already activated)
run:
	uvicorn app.main:app --reload

# Start with explicit host and port (useful for Docker or remote access)
dev:
	uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

# Start using the project venv directly — no manual activation needed
start:
	.venv/bin/uvicorn app.main:app --reload

# Apply all pending Alembic migrations
migrate:
	alembic upgrade head

# Create a new migration — usage: make migration MSG="add jobs table"
migration:
	@if [ -z "$(MSG)" ]; then \
		echo "Error: MSG is required. Usage: make migration MSG=\"describe your change\""; \
		exit 1; \
	fi
	alembic revision --autogenerate -m "$(MSG)"

# Roll back the most recent migration
rollback:
	alembic downgrade -1

# Install dependencies into the active venv
install:
	.venv/bin/pip install -r requirements.txt

# Overwrite requirements.txt with currently installed packages
freeze:
	.venv/bin/pip freeze > requirements.txt

# Run the test suite
test:
	.venv/bin/pytest
