"""add interview rounds table

Revision ID: 1c466a497ce3
Revises: d9958354e8a9
Create Date: 2026-05-21 14:08:34.712038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c466a497ce3'
down_revision: Union[str, Sequence[str], None] = '007ea04b7f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_application_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('interview_type', sa.Enum('phone', 'virtual', 'onsite', 'other', name='interviewtype', native_enum=False, length=20), nullable=False),
    sa.Column('interview_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_rounds_id'), 'interview_rounds', ['id'], unique=False)
    op.create_index(op.f('ix_interview_rounds_job_application_id'), 'interview_rounds', ['job_application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_rounds_job_application_id'), table_name='interview_rounds')
    op.drop_index(op.f('ix_interview_rounds_id'), table_name='interview_rounds')
    op.drop_table('interview_rounds')
    # ### end Alembic commands ###
